---
- name: Check MPM flavor
  fail: 
    msg: "Please specify apache2_mpm as prefork, worker, or event."
  when: apache2_mpm != "prefork" and apache2_mpm != "worker" and apache2_mpm != "event" 
  tags: apache2

- name: Install Apache2
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 86400
  with_items: apache2_packages
  notify: Restart apache
  tags: apache2

- name: Register Apache version
  command: "apache2 -v"
  register: apache2_version
  changed_when: False
  sudo: yes

- name: Apache Unix Domain Sockets (USD) are available when 2.4.10+
  when: 'apache2_version is defined and apache2_version.stdout|match("Server version: Apache/2\\.4\\.1?")'
  set_fact: 
    uds_available: true

- name: Install Apache2 additional pkgs
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 86400
  with_items: apache2_packages_ontop
  notify: Restart apache
  tags: apache2

- name: Disable Apache2 MPM worker and event, if prefork is requested
  apache2_module: 
    name: "{{ item }}"
    state: absent
  with_items:
    - mpm_worker
    - mpm_event
  when: apache2_mpm == "prefork" 
  ignore_errors: true
  notify: Restart apache
  tags: apache2

- name: Enable Apache2 additional modules
  apache2_module: 
    name: "{{ item }}"
    state: present
  with_items: apache2_modules
  notify: Restart apache
  tags: apache2

- name: Disable default apache site
  file:
    path: "/etc/apache2/sites-enabled/000-default"
    state: absent
  notify: Restart apache
  tags: apache2

- name: Disable default-ssl apache site
  file:
    path: "/etc/apache2/sites-enabled/000-default-ssl"
    state: absent
  notify: Restart apache
  tags: apache2

- name: Configure Apache ports
  template:
    src: apache2/ports.conf.j2
    dest: /etc/apache2/ports.conf
  notify: Restart apache
  tags: apache2

- name: Tighten Apache security
  copy:
    src: apache2/security.conf
    dest: /etc/apache2/conf-available/security.conf
  notify: Restart apache
  tags: apache2

- name: Create shared srv folder
  file:
    path: "{{ vhost_base_path }}/shared"
    state: directory
  tags: apache2

- name: Create blocking robots.txt
  copy:
    src: robots.txt
    dest: "{{ vhost_base_path }}/shared/robots.txt"
  tags: apache2

  