---
- name: UnInstall packages for Apache2 MPM worker/event
  package:
    name: "{{ item }}"
    state: absent
    use: apt
  with_items:
    - libapache2-mod-fastcgi
  notify: "Restart apache"
  when: ansible_distribution_release != 'xenial'
  tags: [ provision ]

- name: Install packages for Apache2 MPM worker/event
  package:
    name: "{{ item }}"
    state: present
    use: apt
  with_items:
    - "apache2-mpm-{{ apache2_mpm }}"
  notify: "Restart apache"
  when: ansible_distribution_release != 'xenial'
  tags: [ provision ]

- name: Enable Apache2 worker/event and its dependencies
  command: "a2enmod {{ item }}" 
  with_items:
    - actions
    - proxy_fcgi
    - alias
  register: apache2_module_output
  changed_when: apache2_module_output.stdout.find('{{ item }} already') == -1
  notify: "Restart apache"

- name: Configure Apache event/worker MPM
  template:
    src: apache2/mods/mpm_{{ apache2_mpm }}.conf.j2
    dest: /etc/apache2/mods-available/mpm_{{ apache2_mpm }}.conf
  when: apache2_mpm == "worker" or apache2_mpm == "event"
  notify: "Restart apache"

- name: Disable Apache2 MPM prefork modules
  command: "a2dismod {{ item }}"
  with_items:
    - mpm_itk
    - mpm_prefork
    - php5
  register: apache2_module_output
  changed_when: apache2_module_output.stdout.find('{{ item }} already') == -1
  notify: "Restart apache"
  ignore_errors: true

- name: Disable Apache2 MPM event if worker requested
  command: "a2dismod mpm_event"
  when: apache2_mpm == "worker"
  register: apache2_module_output
  changed_when: apache2_module_output.stdout.find('mpm_event already') == -1
  notify: "Restart apache"

- name: Disable Apache2 MPM worker if event requested
  command: "a2dismod mpm_worker"
  when: apache2_mpm == "event"
  register: apache2_module_output
  changed_when: apache2_module_output.stdout.find('mpm_worker already') == -1
  notify: "Restart apache"

- name: Enable Apache2 worker/event MPM module
  command: "a2enmod mpm_{{ apache2_mpm }}"
  register: apache2_module_output
  changed_when: apache2_module_output.stdout.find('mpm_{{ apache2_mpm }} already') == -1
  notify: "Restart apache"

- name: Enable Apache2 stock mod_proxy_fcgi module
  command: a2enmod proxy_fcgi 
  register: apache2_module_output
  changed_when: apache2_module_output.stdout.find('proxy_fcgi already') == -1
  notify: "Restart apache"
