---
- name: UnInstall packages for Apache2 MPM {{ apache2_mpm }}
  apt:
    pkg: "{{ item }}"
    state: absent
    update_cache: yes
  with_items: 
    - libapache2-mod-fastcgi 
  notify: Restart apache
  tags: apache2

- name: Install packages for Apache2 MPM {{ apache2_mpm }}
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items: 
    - php5-fpm 
    - "apache2-mpm-{{ apache2_mpm }}"
  notify: Restart apache
  tags: apache2

- name: Enable Apache2 {{ apache2_mpm }} and its dependencies
  apache2_module: 
    name: "{{ item }}"
    state: present
  with_items:
    - actions
    - proxy_fcgi
    - alias
  notify: Restart apache
  tags: apache2

- name: Disable Apache2 MPM prefork modules
  apache2_module: 
    name: "{{ item }}"
    state: absent
  with_items: 
    - mpm_itk
    - mpm_prefork
    - php5
  notify: Restart apache
  ignore_errors: true
  tags: apache2

- name: Disable Apache2 MPM event if worker requested
  apache2_module: 
    name: mpm_event
    state: absent
  when: apache2_mpm == "worker" 
  notify: Restart apache
  tags: apache2

- name: Disable Apache2 MPM worker if event requested
  apache2_module: 
    name: mpm_worker
    state: absent
  when: apache2_mpm == "event" 
  notify: Restart apache
  tags: apache2

- name: Enable Apache2 {{ apache2_mpm }} MPM module
  apache2_module: 
    name: mpm_{{ apache2_mpm }}
    state: present
  notify: Restart apache
  tags: apache2

- name: Enable Apache2 stock mod_proxy_fcgi module
  apache2_module: 
    name: proxy_fcgi
    state: present
  notify: Restart apache
  tags: apache2
