---
- name: Create apache2 vhost
  template:
    src: apache2/vhost.conf.j2
    dest: /etc/apache2/sites-available/{{ app_name }}{{ item }}.conf
  with_items:
    - ""
    - ".build"
    - ".bak"

- name: Enable apache2 cur, build and bak vhosts
  file:
    src: /etc/apache2/sites-available/{{ app_name }}{{ item }}.conf
    dest: /etc/apache2/sites-enabled/{{ app_name }}{{ item }}.conf
    state: link
  with_items:
    - ""
    - ".build"
    - ".bak"
  notify: Restart apache
