---
- name: Make sure logs dir exists
  file:
    path: "{{ vhost_base_path }}/{{ app_name }}/logs"
    state: directory

- name: Copy optional rewrite rules file
  template: 
    src: "apache2/rewrite-rules.conf.j2"
    dest: "/etc/apache2/sites-available/{{ app_name }}-rewrite-rules.conf"
  notify: Restart apache
  when: custom_rewrite_rules_path is not defined
  tags: apache2

- name: Copy custom optional rewrite rules file
  template: 
    src: "{{ custom_rewrite_rules_path }}"
    dest: "/etc/apache2/sites-available/{{ app_name }}-rewrite-rules.conf"
  notify: Restart apache
  when: custom_rewrite_rules_path is defined
  tags: apache2

- name: Copy apache2 vhost-common
  template:
    src: apache2/vhost-common.conf.j2
    dest: "/etc/apache2/{{ app_name }}-common{{ item }}.conf"
  with_items:
    - ""
    - ".bak"

- name: Create apache2 vhosts (http)
  template:
    src: apache2/vhost.conf.j2
    dest: "/etc/apache2/sites-available/{{ app_name }}{{ item }}.conf"
  with_items:
    - ""
    - ".bak"

- name: Create apache2 vhosts (https)
  template:
    src: apache2/vhost-ssl.conf.j2
    dest: "/etc/apache2/sites-available/{{ app_name }}-ssl{{ item }}.conf"
  with_items:
    - ""
    - ".bak"

- name: Enable apache2 cur, build and bak vhosts
  file:
    src: "/etc/apache2/sites-available/{{ app_name }}{{ item }}.conf"
    dest: "/etc/apache2/sites-enabled/0-{{ app_name }}{{ item }}.conf"
    state: link
  with_items:
    - ""
    - ".bak"
  notify: Restart apache

- name: Enable apache2 cur, build and bak vhosts (https)
  file:
    src: "/etc/apache2/sites-available/{{ app_name }}-ssl{{ item }}.conf"
    dest: "/etc/apache2/sites-enabled/0-{{ app_name }}-ssl{{ item }}.conf"
    state: link
  with_items:
    - ""
    - ".bak"
  notify: Restart apache
