---
- name: Create shared srv folder
  file:
    path: "{{ vhost_base_path }}/shared"
    state: directory
  tags: apache2

- name: Create blocking robots.txt
  copy:
    src: robots.txt
    dest: "{{ vhost_base_path }}/shared/robots.txt"
  tags: apache2

- name: Create public_html folders
  file:
    path: "{{ vhost_base_path }}/{{ item['host'] }}/public_html"
    state: directory
    owner: "{{ item['user'] }}"
    group: "{{ item['group'] }}"
  with_items: vhost_sites
  tags: apache2

- name: Create public_html symlinks
  file:
    src: "{{ vhost_base_path }}/{{ item['host'] }}/public_html"
    dest: /home/{{ item['user'] }}/public_html
    state: link
    owner: "{{ item['user'] }}"
    group: "{{ item['group'] }}"
  with_items: vhost_sites
  ignore_errors: yes
  tags: apache2

- name: Create log folders
  file:
    path: "{{ vhost_base_path }}/{{ item['host'] }}/logs"
    state: directory
    owner: "{{ item['user'] }}"
    group: "{{ item['group'] }}"
  with_items: vhost_sites
  tags: apache2

- name: Create logs symlinks
  file:
    src: "{{ vhost_base_path }}/{{ item['host'] }}/logs"
    dest: /home/{{ item['user'] }}/logs
    state: link
    owner: "{{ item['user'] }}"
    group: "{{ item['group'] }}"
  with_items: vhost_sites
  tags: apache2

- name: Create apache2 vhosts
  template:
    src: apache2/vhost.conf.j2
    dest: /etc/apache2/sites-available/{{ item['host'] }}.conf
  with_items: vhost_sites
  tags: apache2

- name: Enable apache2 vhosts
  file:
    src: /etc/apache2/sites-available/{{ item['host'] }}.conf
    dest: /etc/apache2/sites-enabled/{{ item['host'] }}.conf
    state: link
  with_items: vhost_sites
  notify: Restart apache
  when: "item['disabled']|default(false) != True"
  tags: apache2
