---
- name: Disable apache2 vhosts
  file:
    path: "/etc/apache2/sites-enabled/{{ item['host'] }}.conf"
    state: absent
  with_items: "{{ apache2_disabled_vhost_sites }}"
  notify: "Restart apache"
