---
# logrotate comes pre-installed on every Linux distribution
- name: setup logrotate.d scripts for the apache logs
  template:
    src: "logrotate.d/apache2.j2"
    dest: "/etc/logrotate.d/{{ item['host'] }}-apache2"
  with_items: vhost_sites
  tags: apache2

- name: setup logrotate.d script for the app specific log
  template:
    src: "logrotate.d/app-log.j2"
    dest: "/etc/logrotate.d/{{ item['app_log'] }}"
  with_items: 
    - vhost_sites
  tags: apache2

- name: setup logrotate.d scripts for daily backups, yeah!
  template:
    src: "logrotate.d/backup.j2"
    dest: "/etc/logrotate.d/{{ item['host'] }}-backup"
  with_items: vhost_sites
  tags: apache2
  