---
# logrotate comes pre-installed on every Linux distribution
- name: setup logrotate.d script for the apache log
  template:
    src: "logrotate.d/apache2.j2"
    dest: "/etc/logrotate.d/{{ item['host'] }}-apache2"
    owner: root 
    group: root
    mode: 0644
  with_items: vhost_sites
  tags: logrotate
