---
- include: apache2.yml

- include: php.yml
  when: apache2_mpm == 'prefork' 

- include: apache2_worker_event.yml
  when: apache2_mpm == 'event' or apache2_mpm == 'worker' 
  
- include: disable-sites.yml
  when: disabled_vhost_sites is defined

- include: logrotate.yml
