---
- include: apache2.yml

- include: mod-php.yml
  when: apache2_mpm == 'prefork' 

- include: apache2_worker_event.yml
  when: apache2_mpm == 'event' or apache2_mpm == 'worker' 
  
- include: create-site.yml

- include: disable-sites.yml
  when: disabled_vhost_sites is defined

- include: logrotate.yml

- name: Restart apache2
  shell: echo "Due to issues like https://github.com/ansible/ansible/issues/11286"
  changed_when: True
  notify: Restart apache
