---
- name: Install PHP pkgs
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ apache2_mod_php5_packages }}"
  notify: "Restart apache"

- name: Install PHP additional pkgs
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ apache2_mod_php5_packages_ontop }}"
  notify: "Restart apache"

- name: Check whether php.ini already exists
  stat:
    path: "/etc/php5/apache2/php.ini"
  register: stat_php_ini

- name: Set php.ini if it doesn't exist already
  template:
    src: "php/apache2.php.ini.j2"
    dest: "/etc/php5/apache2/php.ini"
  when: not stat_php_ini.stat.exists
  notify: "Restart apache"

- name: Set PEAR to install stable packages
  command: pear config-set preferred_state stable
  ignore_errors: true
  register: pear_config
  changed_when: pear_config.stdout.find('config-set succeeded') == -1
